- name: variable override
  hosts: localhost
  vars: #playlevel variable
    Course: "Ansible"
    Duration: "4_months"
  tasks:
  - name: Print DevOps Course
    vars: # Task level variable
      Course: "DevOps"
    ansible.builtin.debug:
      msg: 
      - "Hello, I am Taking {{Course}} Duration is: {{Duration}}"
      - "Overrided The Variable Course"

  - name: Print Ansile Course
    ansible.builtin.debug:
      msg: "Hi, I am Doing {{Course}}"          