- name: variable override
  hosts: localhost
  vars:
    Course: "Ansible"
    Duration: "4_months"
  tasks:
  - name: Print Course
      vars:
        Course: "DevOps"
    ansible.builtin.debug:
      msg: "Hello, I am Taking {{Course}} Duration is: {{Duration}}"
      msg: "Overrided The Variable Course"
      
  - name: Print Course
    ansible.builtin.debug:
      msg: "Hi, I am Doing {{Course}}"          